### Login with valid credentials
POST http://localhost:3001/user/login
Content-Type: application/json

{
    "email":"hd@gmail.com",
    "password":"1234"
}

### Signup

POST http://localhost:3001/user/register
Content-Type: application/json

{
    "email":"hd@gmail.com",
    "password":"1234"
}


### Get products
GET http://localhost:3001